### ISSUE TITLE
Multiline Gum text shows distorted text if centered

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1350]
We have this Gum text:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/ff22d416-dd13-44cc-a3c1-8f1e7cca5a46)

It shows up like this on the game:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/a9801ac1-e753-41c8-a7cd-c63cff34fc36)
Only the second line seems to be distorted.

That text component is center aligned. If we change it to left justified it shows properly:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/f994588d-2fc4-4fd7-adb9-45671a1e0929)

**Comment by vchelaru** [comment]
This problem is due to the way text is aligned to-the-pixel internally. By default text positions are snapped to the pixel to reduce the chances of incorrect font rendering when a Text object has a position which includes a fraction of a pixel. This can happen if a Text object has a velocity that makes it move smoothly, or if its XUnits results in a fractional pixel value (such as percent of parent).

When a Text instance is rendered, its top-left corner is snapped to the pixel. This works fine if a Text object has a single line, even if the Text is centered because its boundaries are calculated and the top-left is adjusted appropriately.

However, if the text is centered and has multiple lines (as shown above), then the widest line determines the left edge which is used for adjustment. All other lines (shorter lines) react to this offset, which may result in the Text being offset by a half-pixel.

The fix for this is that each line of text should adjust its own X offset rather than the entire Text object having its XOffset adjusted as a whole since each line may need a separate offset.

I need to spend some time looking at the rendering code to see if this is a complicated issue or if it's an easy fix.

**Comment by vchelaru** [comment]
Fixed in Gum 

2962416bbc84d842dfe596bbf8c1004b42cc865f

**Comment by mfigueirido** [comment]
Sorry, updated to latest but the issue is still present. Maybe there's something else happening on my project?

**Comment by vchelaru** [comment]
Fixed...again.
